config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'apps/' => 'apps#index', as: :apps
  post 'apps/' => 'apps#create'
  patch 'apps/:id' => 'apps#update', as: :app
  delete 'apps/:id' => 'apps#destroy'
  get 'audiences/' => 'audiences#index', as: :audiences
  post 'audiences/' => 'audiences#create'
  patch 'audiences/:id' => 'audiences#update', as: :audience
  delete 'audiences/:id' => 'audiences#destroy'

  get 'ideas/' => 'ideas#index', as: :ideas
  post 'ideas/' => 'ideas#create'
  patch 'ideas/:id' => 'ideas#update', as: :idea
  delete 'ideas/:id' => 'ideas#destroy'

end

app/models/app.rb
class App < ActiveRecord::Base
	has_many :ideas

	validates :name, presence: true 
end

app/models/audience.rb
class Audience < ActiveRecord::Base
	has_many :ideas

	validates :name, presence: true 
end

app/models/idea.rb
class Idea < ActiveRecord::Base
	belongs_to :app
	belongs_to :audience
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
	def index
		@apps = App.all.order(:name)
	end

	def create
		@app = App.new(params.require(:app).permit(:name))
		if @app.save 
			redirect_to root_path
		else
			redirect_to root_path
		end
	end

	def update
		@app = App.find(params[:id])
		@app.update(params.require(:app).permit(:name))
		
		redirect_to apps_path
		
	end
	def destroy
		@app = App.find(params[:id])
		@app.ideas.destroy_all
		@app.destroy
		
		redirect_to apps_path
		
	end
end

app/controllers/audiences_controller.rb
class AudiencesController < ApplicationController
	def index
		@audiences = Audience.all.order(:name)
	end

	def create
		@audience = Audience.new(params.require(:audience).permit(:name))
		if @audience.save 
			redirect_to root_path
		else
			redirect_to root_path
		end
	end

	def update
		@audience = Audience.find(params[:id])
		@audience.update(params.require(:audience).permit(:name))
		
		redirect_to audiences_path
		
	end
	def destroy
		@audience = Audience.find(params[:id])
		@audience.ideas.destroy_all
		@audience.destroy
		
		redirect_to audiences_path
		
	end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
	def index
		@ideas = Idea.all.order(upvote: :desc)
	end

	def create
		@app = App.find(params[:app_id])
		@audience = Audience.find(params[:audience_id])
		@idea = Idea.create(app:@app, audience:@audience)
		redirect_to root_path

	end

	def destroy
		@idea = Idea.find(params[:id])
		@idea.destroy
		
		redirect_to ideas_path
		
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@idea = Idea.new(app:App.order("RANDOM()").first, audience:Audience.order("RANDOM()").first)
  	@app = App.new
  	@audience = Audience.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/audiences_helper.rb
module AudiencesHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/apps/index.html.erb
<% @apps.each do |app| %>

<%= form_for app do |f| %>

  <div class="col-md-6 form-group">
	<div class="col-md-10" >
    	<%= f.text_field :name, class: "form-control" %>
    </div>
	<div class="col-md-2 col-form-label">
		<%= link_to("x", app_path(app), method: :delete, data: {confirm: "You sure?"}) %>
	</div>
	<%= f.submit "edit an app!", :style => "display: none;"  %>
  </div>
  
<% end %> 

<% end %>

app/views/audiences/index.html.erb
<% @audiences.each do |audience| %>
<%= form_for audience do |f| %>
  <div class="col-md-6 form-group">
	<div class="col-md-10" >
    	<%= f.text_field :name, class: "form-control" %>
    </div>
	<div class="col-md-2 col-form-label">
		<%= link_to("x", audience_path(audience), data: {method: :delete, confirm: "You sure?"}) %>
	</div>
	<%= f.submit "edit an audience!", :style => "display: none;"  %>
  </div>
<% end %> 
<% end %>

app/views/ideas/index.html.erb
<% @ideas.each do |idea| %>
	<h2>
		<%= idea.app.name.titleize%> for <%= idea.audience.name%>
		<span><%= link_to("x", idea_path(idea), method: :delete, data: {confirm: "I believe this is a terriable idea, and this app should never be made"}) %></span>
	</h2>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IdeaGenerator</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">
   <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to("Home", root_path) %></li>
        <li><%= link_to("list of the apps", apps_path) %></li>
        <li><%= link_to("List of the audiences", audiences_path) %></li>
        <li><%= link_to("Honorable ideas", ideas_path) %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
  </nav>
<div id="top-margin">
<%= yield %>
<div>
</body>
</html>

app/views/welcome/index.html.erb
		<div id="top">
			<H1>Project Topic Generator v3.5</H1>
		</div>

		<section id="container">
			<div ><h2><%= @idea.app.name.titleize%> for <%= @idea.audience.name%></h2>
			</div>
            
            <%= link_to image_tag("https://d30y9cdsu7xlg0.cloudfront.net/png/100266-200.png", size: "50x50", alt: "Edit Entry"), ideas_path(:audience_id => @idea.audience.id, :app_id => @idea.app.id), :method => :post %>
<br>
<br>
			<%= button_to "Give me another idea", root_path, :method => :get %>
		</section>

<%= form_for @app do |f| %>

  <div class="col-md-2 col-md-offset-3"">

    <%= f.text_field :name %>

 <%= f.submit "Add an app!" %>
  </div>
<% end %> 


<%= form_for @audience do |f| %>

  <div class="col-md-2 col-md-offset-2">

    <%= f.text_field :name %>

 <%= f.submit "Add an audience!" %>
  </div>
<% end %> 